### ISSUE TITLE
你好，自编译请教

### ISSUE THREAD

**Issue by jiaoyilun** [SudaMod/android_external_suda_SudaSDKs#1]
你好，感谢你们提供开源代码，我刚开始学习自编译cm12，现在想学着合并你们的来电归属地代码，里面用到SudaSDK这个包，我已经按照您的default.xml把SudaSDKs这个project加入到我的default.xml，代码已经正常同步了，但是打包时始终通不过编译，提示找不到com.a1os........这个包，好像没打包进去似的，请问该怎么处理，求指导，期待您的回复，谢谢

**Comment by ghbhaha** [comment]
Dialer/Android.mk你看下 其他都是一个理

------------------ 原始邮件 ------------------
发件人: "JIaoYilun";notifications@github.com;
发送时间: 2015年11月2日(星期一) 上午9:40
收件人: "SudaMod/android_external_suda_SudaSDKs"android_external_suda_SudaSDKs@noreply.github.com; 

主题: [android_external_suda_SudaSDKs] 你好，自编译请教 (#1)

你好，感谢你们提供开源代码，我刚开始学习自编译cm12，现在想学着合并你们的来电归属地代码，里面用到SudaSDK这个包，我已经按照您的default.xml把SudaSDKs这个project加入到我的default.xml，代码已经正常同步了，但是打包时始终通不过编译，提示找不到com.a1os........这个包，好像没打包进去似的，请问该怎么处理，求指导，期待您的回复，谢谢

**Comment by jiaoyilun** [comment]
看到了，非常感谢

**Comment by jiaoyilun** [comment]
看到了，非常感谢
